### ISSUE TITLE
CTD on second New Game after returning to main menu

### ISSUE THREAD

**Issue by dervishxgit** [ForgottenGlory/Masterstroke#1]
**Masterstroke Version**
All versions since release, currently alpha-4.

**Describe the bug**
Crash second time selecting 'New Game'.

**To Reproduce**
After starting a new game, or loading an existing, return to main menu, and select 'New Game'. CTD follows.

**Expected behavior**
Should be able to start new game as many times as we'd like.

**Additional context**
Common elements observed in crashlogs:
Possible relevant objects (3)
[Crash_2022_1_10_18-14-20.txt](https://github.com/ForgottenGlory/Masterstroke/files/7873547/Crash_2022_1_10_18-14-20.txt)

{
  [   0]    NiNode(Name: null)
  [   3]    NiCamera(Name: `WorldRoot Camera`)
  [  54]    NiCamera(Name: null)
}

**Comment by zarantha** [comment]
i seem to no longer have this bug suddenly
the only recent changes i think i have are using fnis instead of nemesis, and disabling that map marker option in po3's tweaks

**Comment by ForgottenGlory** [comment]
I still get this after switching to FNIS and disabling the map marker option. Unsure of cause.

**Comment by dervishxgit** [comment]
Can confirm this bug still exists in alpha-5
[Crash_2022_1_18_15-41-54.txt](https://github.com/ForgottenGlory/Masterstroke/files/7892977/Crash_2022_1_18_15-41-54.txt)

**Comment by dervishxgit** [comment]
Also, just in case it matters, it is loading any new game after loading any save as well, not just the second time loading new game.
[Crash_2022_1_18_16-25-12.txt](https://github.com/ForgottenGlory/Masterstroke/files/7893034/Crash_2022_1_18_16-25-12.txt)

**Comment by zarantha** [comment]
The crash seems to be related to females only. for me anyway.

seems fixed after:
- updated engine fixes to latest
- updated mu joint to latest
- moved papyrusutil to late loaders
- reverted ap to 2.4
- reinstalled vc after win 11 upgrade 🙄

**Comment by ForgottenGlory** [comment]
Fixed Alpha 2
