### ISSUE TITLE
Spank That Ass breaks occasionally

### ISSUE THREAD

**Issue by Eikonoklaste** [ForgottenGlory/Masterstroke#10]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[Masterstroke Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Masterstroke Version**
Alpha2

**Describe the bug**
Spank That Ass will occasionally bug if an NPC is trying to reach you for a furniture spank event but for whatever reason can't. This causes spank events to cease entirely while the NPC constantly follows you, pushing you and sometimes teleporting to you in dungeons. *Edited to add that this appears to be an issue within the mod itself and has been reported on the LL forum as recently as 12/28/21.
This has the added effect of freezing the Spank That Ass MCM menu so that the options in it will never load when clicking Settings.

**To Reproduce**
It's a bit random but seems to happen if you use a furniture piece, let an NPC try to get to you for a spank event, then leave the piece and not allow them to finish the spank.
Rolling back to a save before the breakage seems to be the only solution for now.

**Expected behavior**
No busted spanking.

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by Eikonoklaste** [comment]
Link to relevant thread in LL: https://www.loverslab.com/topic/123745-spank-that-ass-se/?do=findComment&comment=3149702

**Comment by ForgottenGlory** [comment]
Fixed Alpha 3
