### ISSUE TITLE
Floating book in Nilheim

### ISSUE THREAD

**Issue by zarantha** [ForgottenGlory/Masterstroke#109]
**Masterstroke Version**
Masterstroke 0.6.0 - Beta 6 RC2

**Describe the bug**
Floating book

**To Reproduce**
Book is in the tower in Nilheim

**Expected behavior**
Book should be on the floor, or we're missing a table.

**Screenshots**
![enb2022_6_17_01_01_59](https://user-images.githubusercontent.com/31942539/174325580-74d9e233-2501-4ec8-919f-f883990bf77c.png)

![enb2022_6_17_01_02_45](https://user-images.githubusercontent.com/31942539/174325784-cb84dbb4-fb03-4e98-9601-b179c5a6c35c.png)

**Comment by ForgottenGlory** [comment]
fixed
