### ISSUE TITLE
Non hostile NPCs in Helgen torture room

### ISSUE THREAD

**Issue by zarantha** [ForgottenGlory/Masterstroke#110]
**Masterstroke Version**
Masterstroke 0.6.0 - Beta 6 RC2

**Describe the bug**
The torturer, his apprentice, and some Stormcloaks are all just hanging out together in the torture room.

**To Reproduce**
Enter the tower in Helgen and head down to the dungeon.

**Expected behavior**
They should be fighting when the PC enters, or dead.

**Additional context**
I just walked into Helgen strait from Lorkhan. I was trying to start the main quest and didn't see anything to pick on of those factions, so I was looking for Ralof and Hadvar. Didn't find them btw, the cave exit is blocked, and the bridge switch is gone.

**Comment by ForgottenGlory** [comment]
fixed
