### ISSUE TITLE
Broken links in the readme document.

### ISSUE THREAD

**Issue by catapsis** [ForgottenGlory/Masterstroke#12]
**Section**
Before You Start

**Description**
In the Important Links subsection, the link to the [Masterstroke Build Planner](https://thehajo.github.io/Masterstroke/) is throwing a 404 error.

In the Screenshots subsection, the link to the [Masterstroke Screenshot Gallery](https://www.fgsmodlists.com/Masterstroke/screenshots) is throwing a 404 error.

**Comment by ForgottenGlory** [comment]
Fixed
