### ISSUE TITLE
Public whore questline freeze

### ISSUE THREAD

**Issue by ForgottenGlory** [ForgottenGlory/Masterstroke#129]
Is bug?: Confirm

Read the readme?: Confirm

List Version: v1.0.0

Reproducable?: Yes

Discord Username: Bunnystack#5565

Rule 11?: No

Type: Quest bug

Summary: Public whore questline freeze

Details: When helping Belethor for the public whore questline in Whiterun, the quest will freeze when the 2nd visitor arrives. Dialogue will stop and the NPCs will stand still. The only way to leave is to reload a previous save. 

Steps to reproduce: Talk to Jarl Barlgruuf and select the "Do you have any work for me, Jarl?" dialogue option to start the quest. Then talk to Thane Fausus and select "The Jarl told me to see you." Complete the first of the quest and return to Thane Fausus and he will tell you to help three shopkeepers. Go to Belethor's and select "Is there anything I can help you with?". 

Crash log: 

Screenshots:

**Comment by ForgottenGlory** [comment]
Unable to replicate

**Comment by PotatoKnight** [comment]
I did this questline and had the exact same issue, but moving away from the spot Belethor puts you in, and moving back to it, resolves the issue (or at least it did for me). I'm not certain if I was supposed to be able to move though, maybe that's part of the problem.
