### ISSUE TITLE
Characters t-posing on new game start

### ISSUE THREAD

**Issue by Retromess** [ForgottenGlory/Masterstroke#13]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[Masterstroke Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**
[Crash_2021_12_26_11-58-5.txt](https://github.com/ForgottenGlory/Masterstroke/files/8147444/Crash_2021_12_26_11-58-5.txt)
[Crash_2022_1_17_15-44-45.txt](https://github.com/ForgottenGlory/Masterstroke/files/8147445/Crash_2022_1_17_15-44-45.txt)
[Crash_2022_1_23_16-9-0.txt](https://github.com/ForgottenGlory/Masterstroke/files/8147446/Crash_2022_1_23_16-9-0.txt)
[Crash_2022_1_23_16-14-12.txt](https://github.com/ForgottenGlory/Masterstroke/files/8147447/Crash_2022_1_23_16-14-12.txt)
[Crash_2022_1_23_16-15-46.txt](https://github.com/ForgottenGlory/Masterstroke/files/8147448/Crash_2022_1_23_16-15-46.txt)
[Crash_2022_1_23_16-17-30.txt](https://github.com/ForgottenGlory/Masterstroke/files/8147449/Crash_2022_1_23_16-17-30.txt)
[Crash_2022_1_23_16-20-44.txt](https://github.com/ForgottenGlory/Masterstroke/files/8147450/Crash_2022_1_23_16-20-44.txt)
[Crash_2022_1_23_19-51-34.txt](https://github.com/ForgottenGlory/Masterstroke/files/8147451/Crash_2022_1_23_19-51-34.txt)
[Crash_2022_1_23_20-28-30.txt](https://github.com/ForgottenGlory/Masterstroke/files/8147452/Crash_2022_1_23_20-28-30.txt)

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Masterstroke Version**
Masterstroke Beta 1

**Describe the bug**
Upon starting the game, my character and all NPCs were T-posing and producing no animations. I ran the normal first install steps, waited upwards of 15 minutes, but they did not animate.

**To Reproduce**
Load a new save following the readme, running MCM Recorder etc.

**Expected behavior**
Characters should animate when moving, attacking, etc.

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
I saved my game, closed it, and ran FNIS from MO2. After running it, I loaded my save up and all characters were animating as normal.

**Comment by ForgottenGlory** [comment]
Fixed
