### ISSUE TITLE
Archery's WarArrows unbalanced

### ISSUE THREAD

**Issue by Dace617** [ForgottenGlory/Masterstroke#130]
**Masterstroke Version**
1.0

**Describe the bug**
Archery's War Arrows require steel smithing perk, but require Iron to make, they also have a damage level equivalent to Elven arrows
Warbow is also missing Engarde's keywords from the synthesis patcher

**Expected behavior**
slightly less op arrows.

**Additional context**
attached a patch to the trello that fixes the keywords on the bow and rebalances the war arrows to require steel and steel arrows to make, effectively making them an upgrade of steel arrows with appropriate damage equivalent to orcish arrows.

**Comment by ForgottenGlory** [comment]
fixed
