### ISSUE TITLE
Valmira's Clothing is unfitting, and her weapon OP

### ISSUE THREAD

**Issue by Dace617** [ForgottenGlory/Masterstroke#131]
**Masterstroke Version**
1.0

**Describe the bug**
Valmiria's "crossbow" and arrows are absurdly overpowered, and her armour is unfitting for the game.

**Additional context**
Patch on the Trello to replace her custom items with Fem-Tsun armour and a normal crossbow/bolts. removed crafting of her custom gear. I let her keep her horns. Optional edit to this patch would be to mark her crossbow and bolts as unplayable to stop console command shenanigans. up to you.

**Comment by ForgottenGlory** [comment]
fixed
