### ISSUE TITLE
My follower puts me in bindings I can't get out of

### ISSUE THREAD

**Issue by ForgottenGlory** [ForgottenGlory/Masterstroke#139]
Is bug?: Confirm

Read the readme?: Confirm

List Version: 1.0.1

Reproducable?: Yes

Discord Username: Warden#9639

Rule 11?: No

Type: Gameplay (objects which cannot be activated or other gameplay related bugs)

Summary: My follower puts me in bindings I can't get out of

Details: Recorder will offer to put me in bindings, but is unable to find any on my person. She summons some (she doesn't have them in her inventory prior to this event) and puts a Yoke, a Ballgag, and a blindfold on me. When asked to take it off, she is unable to find the key, and the key is nowhere in the cell. I am unable to ask NPCs to help as the ballgag prevents me from talking. 

I have had this happen in 3 separate instances, and I've seen two other users talk about it without as much detail. Juliett#5574 and Thermedge#3932.

Steps to reproduce: - Get Recorder as an NPC. I haven't tested this with any other followers yet.
- Play until Recorder gets a "devious expression" and offers to put you in bindings. This may take some time and relationship building to trigger.
- She will always put your PC in a yoke, a ballgag and a blindfold.

I got this to trigger a 4th time, but this time she put my arms in different restraints. I was able to escape from those, but I am still unable to do anything about the ball gag without the key.

Crash log: 

Screenshots:

**Comment by TheCampingOwl** [comment]
Not a bug, you need to talk to a Blacksmith in order to get it cut off if you don't have the key for it.

If you don't have bondage equipment, your follower will pull some from the realm of bullshit in order to bind you. This goes for all followers, not just Recorder.

**Comment by ForgottenGlory** [comment]
fixed
