### ISSUE TITLE
Left Handed Attack

### ISSUE THREAD

**Issue by Asmondar** [ForgottenGlory/Masterstroke#14]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[Masterstroke Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Masterstroke Version**
Beta 1

**Describe the bug**
Left handed melee weapon doesn't work. For me it only blocks. Magic works, fine in both right and left. When I put flames in right, and dagger in left, I can't attack with dagger. When I reverse them and press flames, it blocks.

**To Reproduce**
put a weapon/dagger in left hand and try to attack something.

**Expected behavior**
To be able to attack with both left or right hand with weapons?

**Screenshots**
![Blocking Skyrim](https://user-images.githubusercontent.com/67242048/155859771-39f8fc04-a833-45e7-8121-a05d522b9d36.jpg)
Attempting to cast flames with left hand.

**Additional context**
I do have multiple installs of modlists, but none have this bug. Selected Random start, started by the Dwarven Ruins around Dawnstar, Alftand.

**Comment by DrFrosty21** [comment]
not a bug, press shift+ right click
https://www.nexusmods.com/skyrimspecialedition/mods/25673
