### ISSUE TITLE
MCM Adjustments 

### ISSUE THREAD

**Issue by DrFrosty21** [ForgottenGlory/Masterstroke#141]
**DD Helpers**
No items locked without a key: enabled

**SLSO**
Pleasure Priority: Partner

---
**Suggestions** 
DD
disable device hider, it hides parts of bikini armors
(or you remember the settings dnddc used, I didn't)

MME
disable Exhaustion debuff, people think Sunhelm is bugged cuz the widget doesn't match. 

Smoothcam / Engarde
some of the cam presets use V to switch the 3rd person shoulder view, Engarde use V to dodge, maybe change one of them

SLDefeat (this is based entirely on my personal preferences!)
Player as victim: turn off Wound, Exhaustion, Stun modifiers 
(makes it more clear when you get defeated and gives more leeway)

**Comment by ForgottenGlory** [comment]
done
