### ISSUE TITLE
some names shows up in squares 

### ISSUE THREAD

**Issue by ForgottenGlory** [ForgottenGlory/Masterstroke#145]
Is bug?: Confirm

Read the readme?: Confirm

List Version: v1.0.1 

Reproducable?: Yes

Discord Username: nashironeko #5069

Rule 11?: No

Type: names of some objects are unreadable (squares)

Summary: some names shows up in squares 

Details: 

Steps to reproduce: discovered this issue after I first installed the list, and went straight to whiterun, and it never went away.

Crash log: 

Screenshots: https://drive.google.com/file/d/1h6nZG1B8TJ6svyT6vSLQ1stPYBQ63yER/view?usp=sharing

**Comment by DrFrosty21** [comment]
list was modified

**Comment by ForgottenGlory** [comment]
Rule 11
