### ISSUE TITLE
AI is deaf and blind

### ISSUE THREAD

**Issue by DrFrosty21** [ForgottenGlory/Masterstroke#149]
**Masterstroke Version**
1.0.1

**Describe the bug**
The AI has trouble finding friends and enemies indoors, which sometimes leads to an _endless_ "search mode".

**To Reproduce**
Visit Jorrvaskr, the two NPCs doing the brawl on the first visit are unable to find each other. Same goes for combat, for example when you get defeated but your follower hasn't caught up yet, _eternally_ searching for the enemy.

**Expected behavior**
AI not being blind and deaf

**Screenshots**
https://imgur.com/a/n1qKI5y

**Additional context**
Updating [Realistic AI Detection](https://www.nexusmods.com/skyrimspecialedition/mods/2345/) and using the Medium Interior Medium Exterior file helps to reduces the likelihood of this scenario.

**Comment by ForgottenGlory** [comment]
fixed
