### ISSUE TITLE
Quick Light and Take Notes! Journal aren't hotkeys aren't updated when running MCM Recorder

### ISSUE THREAD

**Issue by Listerw** [ForgottenGlory/Masterstroke#15]
**Masterstroke Version**
Masterstroke Beta 1 (after the T-posing fix)

**Describe the bug**
After following the character creation and MCM configuration steps, Quick Light hotkey is still X and my `Take Notes!` Journal hotkey is still X.

**To Reproduce**
Create a new character following https://www.fgsmodlists.com/masterstroke/mcm/. (Create a character, save, load)
Run the MCM recorder, Save, Load.

Try switching quick light on with End. It won't work.
Check the MCM, the hotkey is still X.

This hotkey will also open the `Take Notes!` Journal and checking its MCM will show the hotkey is also still X.

**Expected behavior**
The quick light and journal hotkeys should be updated.

**Comment by Listerw** [comment]
I haven't checked the other MCMs, but I'll go through them and add to this.

**Comment by Listerw** [comment]
These are the discrepancies I found between my MCM settings after running the recorder and the documentation https://www.fgsmodlists.com/masterstroke/mcm/#mcm-documentation. I'm not sure which one of these is supposed to be correct, since some of these hotkeys could be valid but just not documented in there.

Gender Bender none of the steps are done:
```
    Mod Active: Enabled
    Gender Quick Change: Numpad 7
    No Effects: Enabled
```

Leadership MCM hotkey is . or > instead of K.

Obody hotkey is U instead of Page Dn

Smoothcam swap shoulder hotkey V instead of PgUp

Toyful Tempations Trap method is Rushed instead of Toys

**Comment by ForgottenGlory** [comment]
Gender Bender is optional and isn't enabled by default, but I will look into the rest. Thanks.

**Comment by ForgottenGlory** [comment]
Waiting for an update to MCM Recorder which should fix the hotkeys not being set issue
