### ISSUE TITLE
A-Pose on first start up

### ISSUE THREAD

**Issue by DrFrosty21** [ForgottenGlory/Masterstroke#150]
**Masterstroke Version**
1.0.1

**Describe the bug**
The player (and sometimes a few npcs) a-pose for a while after the first start up of the game. Goes away after a short wait.

**To Reproduce**
restart the game, load a save

**Expected behavior**
not a-posing

**Screenshots**
![image](https://user-images.githubusercontent.com/85462940/177106582-6093e079-d2b5-4e2a-b591-52546fbe35f1.png)

**Additional context**

**Comment by TwistedModding** [comment]
not a bug, dar is caching animations.
