### ISSUE TITLE
Submissive Lola quests give too much experience

### ISSUE THREAD

**Issue by LunaPapilio** [ForgottenGlory/Masterstroke#151]
The quests you get when using the mod is too much, it results in being able to easily and quickly fly through levels. We can either remove XP from her quests altogether, or increase the time between quests via MCM.

**Comment by LunaPapilio** [comment]
![image](https://user-images.githubusercontent.com/77394294/177216872-29365ebe-61cc-4c7d-ac6e-47f6d2674ba3.png)
![image](https://user-images.githubusercontent.com/77394294/177216879-6d0d850c-817b-49d2-9e40-936d7f8233e1.png)

MCM settings set like this fix the problem according to Eiko, settings and shots are his

**Comment by ForgottenGlory** [comment]
fixed
