### ISSUE TITLE
Vampire lord form of Lord Harkon is partially missing

### ISSUE THREAD

**Issue by DrFrosty21** [ForgottenGlory/Masterstroke#152]
**Masterstroke Version**
1.0.1

**Describe the bug**
Titel

**To Reproduce**
follow dawnguard quest till you meet Harkon 

**Expected behavior**
I'm sure he's a beauty beneath his curt of invisibility.

**Screenshots**
![image](https://user-images.githubusercontent.com/85462940/177220570-cc047a4a-53ed-4b4f-be41-936ab9577b4a.png)
![image](https://user-images.githubusercontent.com/85462940/177220629-36c87aa1-1bdc-45e3-ba81-73d6366887d1.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
should be fixed
