### ISSUE TITLE
Shandar is not placed in Dead Man's Drink in Falkreath

### ISSUE THREAD

**Issue by zarantha** [ForgottenGlory/Masterstroke#155]
**Masterstroke Version**
Masterstroke v1.0.2

**Describe the bug**
Shandar is not in the inn in Falkreath

**To Reproduce**
Go to the inn and look around

**Expected behavior**
He should be somewhere in the inn.

**Additional context**
The fix is to flip the order of his ESPs. The order should be:
ShandarStandaloneFollowerCore.esp
ShandarStandaloneFollower.esp

With the list's current load order, he is summonable with player.placeatme. 
He just doesn't show up on his own as far as I can tell. And he doesn't seem to be stuck in a wall or outside the cell. As far as I can tell, he's just not spawned unless you make a copy of him with player.placeatme.

RefID should be FE0E6800 for an unmodded list.
This is modded:
![image](https://user-images.githubusercontent.com/31942539/177470615-f64edd79-01ec-4832-8af6-8feb47878745.png)

**Comment by ForgottenGlory** [comment]
Fixed
