### ISSUE TITLE
Follower Juliada - Uses custom body

### ISSUE THREAD

**Issue by DrFrosty21** [ForgottenGlory/Masterstroke#157]
**Masterstroke Version**
1.0.1

**Describe the bug**
Juliada uses her own custom body, conflicting with OBody.

**To Reproduce**
Visit her in Morthal Jail

**Expected behavior**
fitting outfits

**Screenshots**
![enb2022_7_8_00_02_47](https://user-images.githubusercontent.com/85462940/177880592-645a3712-6849-4b03-816c-42b4817a7212.png)
![enb2022_7_8_00_02_48](https://user-images.githubusercontent.com/85462940/177880625-55e0cdf3-ef59-40d7-9ba4-dc4f6f8c23ec.png)

**Additional context**

**Comment by ForgottenGlory** [comment]
fixed
