### ISSUE TITLE
Recorder can't wear her skirt

### ISSUE THREAD

**Issue by zarantha** [ForgottenGlory/Masterstroke#159]
**Masterstroke Version**
MS 1.0.2

**Describe the bug**
Because of SOS, recorder can't wear her both her skirt and shirt at the same time

**To Reproduce**
Observe, or play with her clothing. If you take her stuff and just give her the skirt back, she wears it and it is visible. If you give her her shirt, it swaps to the shirt instead of wearing both.

**Expected behavior**
She should be completely dressed.

**Additional context**

Fix if you don't want to patch it yourself:
https://www.nexusmods.com/skyrimspecialedition/mods/69680

**Comment by ForgottenGlory** [comment]
fixed
