### ISSUE TITLE
Map of Skyrim shows floating icons and generally weird looking.

### ISSUE THREAD

**Issue by Yakuuuuuuuuuuuu** [ForgottenGlory/Masterstroke#16]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[Masterstroke Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

**Masterstroke Version**
Masterstroke beta 1 (.2)

**Describe the bug**
Map of skyrim opens a bugged map with icons floating. See screenshots.

**To Reproduce**
Equip map of skyrim and press "M"

**Expected behavior**
I don''t know which mod has added the map, so im unsure of the expected behavior.

**Screenshots**
![image](https://user-images.githubusercontent.com/100487780/155860413-c77fd27d-9452-400e-8d37-ad05a59aac94.png)
![image](https://user-images.githubusercontent.com/100487780/155860432-125e65f2-558d-4882-8b2c-5bd6794eccbe.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
