### ISSUE TITLE
Alvor's quest for learning blacksmithing not working

### ISSUE THREAD

**Issue by Arcannum** [ForgottenGlory/Masterstroke#18]
**If you are reporting a crash to the desktop, please attach your NET Script Framework crash log. This can be found in `[Masterstroke Install folder]\mods\Files Generated during play sessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Masterstroke Version**
Masterstroke 0.1.0 - Beta 1

**Describe the bug**
Alvor's quest where he teaches you the basics of how to craft by asking the PC to craft an Iron Dagger doesn't proceed even after crafting an Iron Dagger. 

**To Reproduce**
Talk to Alvor to initiate the quest by choosing the dialogue option for  "Do you need any help around the forge?" and then proceeding to craft an iron dagger. After the Dagger has been crafted, Alvor doesn't react to the crafted dagger and has no option to proceed with the quest either.

**Expected behavior**
The quest should proceed to Alvor asking the Dragonborn to temper the crafted Iron Dagger using the Grindstone.

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object, or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by Yeomans** [comment]
Quest worked first time for me. I had this happen in another list before, and reloading save and starting the quest worked.

**Comment by Arcannum** [comment]
Tried reloading save a few times, tried restarting from a fresh save, and even tried reinstalling the mod-list but it still doesn't progress further.

**Comment by Arcannum** [comment]
It worked after forging the dagger and switching cells and talking to Alvor again.
