### ISSUE TITLE
New effects discovered when crafting potions aren't being shown in the UI.

### ISSUE THREAD

**Issue by catapsis** [ForgottenGlory/Masterstroke#19]
**Masterstroke Version**
Beta 1

**Describe the bug**
When discovering new effects when crafting potions, the discovered effects aren't shown in the potion creation popup. See attached screenshot.

**To Reproduce**
Craft a potion that causes you to learn new ingredient properties. 

**Expected behavior**
The potion creation popup should list the newly discovered effects.

**Screenshots**
![enb2022_2_26_23_11_26](https://user-images.githubusercontent.com/62223653/155870964-aa4393a9-0f1d-4c31-b5ec-3ccd3eb7e1d3.jpg)

**Additional context**
The 21:9 UI optional mod was being used.

**Comment by ForgottenGlory** [comment]
Probably related to #5
