### ISSUE TITLE
CTD when clicking a location on the map

### ISSUE THREAD

**Issue by zarantha** [ForgottenGlory/Masterstroke#2]
**Masterstroke Version**
alpha 4

**Describe the bug**
CTD occurred when clicking Whiterun to fast travel or add a marker.

**To Reproduce**
Open the map.
Click a location that you are not at.

**Expected behavior**
A message that you cannot fast travel, or a marker placed.

**Additional context**
Looks like a conflict between po3's tweaks and disable fast travel.

To fix, disable this:
po3_Tweaks.ini
;Allows placing map markers near fast travel destinations when fast travel is disabled
Map Marker Placement Fix = true

[Crash_2022_1_16_2-25-20.txt](https://github.com/ForgottenGlory/Masterstroke/files/7877970/Crash_2022_1_16_2-25-20.txt)
[Crash_2022_1_16_16-29-27.txt](https://github.com/ForgottenGlory/Masterstroke/files/7877980/Crash_2022_1_16_16-29-27.txt)

**Comment by ForgottenGlory** [comment]
Fixed Pre-Alpha 5
