### ISSUE TITLE
Ground texture bug

### ISSUE THREAD

**Issue by Yeomans** [ForgottenGlory/Masterstroke#20]
**Masterstroke Version**
Beta 1.

**Describe the bug**
Some ground textures appear smeared. Similar to when EnableTerrainParallax is enabled in ENB, however it is disabled (by default).

**To Reproduce**
Look at ground textures. Issue more noticeable in first person. Some textures are worse than others:

**Expected behavior**
Non-smeared textured.

**Screenshots**
![image](https://user-images.githubusercontent.com/22068629/155874087-07552a08-8c79-4f6b-a8eb-02b0595df613.png)
![image](https://user-images.githubusercontent.com/22068629/155874097-c2fe1284-0a4d-4fb5-9165-0302c4701bab.png)
![image](https://user-images.githubusercontent.com/22068629/155874188-5fd4423f-7b36-466d-86b1-eeb8cb9416bf.png)

**Additional context**

**Comment by Yeomans** [comment]
It seems that one way to fix this is to disable "SSE parallax Shader Fix (BETA)"

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
