### ISSUE TITLE
Fur boots invisible

### ISSUE THREAD

**Issue by Yeomans** [ForgottenGlory/Masterstroke#21]
**Masterstroke Version**
Beta 1

**Describe the bug**
Fur boots on female PC are invisible

**To Reproduce**
Wear fur boots as female

**Expected behavior**
Visible mesh

**Screenshots**
![image](https://user-images.githubusercontent.com/22068629/155874271-810e9a65-5d42-4db4-8375-6c456237b1d5.png)
![image](https://user-images.githubusercontent.com/22068629/155874287-26bcdbcf-7ad6-4934-a6ef-96168278f46b.png)
![image](https://user-images.githubusercontent.com/22068629/155874296-cbf7a21a-1567-4a55-9ebf-1ea13138067f.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
