### ISSUE TITLE
Mouth morphs seem wrong when using Toys

### ISSUE THREAD

**Issue by Banzaibear** [ForgottenGlory/Masterstroke#22]
**Masterstroke Version**
Beta 1

**Describe the bug**
Mouth morphs seem incorrect,

**To Reproduce**
Tested on two different races (DE/Human), DE was worse.

**Expected behavior**
Mouths should fit more snugly around the gags!

**Screenshots**

![Screenshot (33)](https://user-images.githubusercontent.com/72049103/155875027-6d65c6b2-ca31-4798-9dec-bbd36d0ad316.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
