### ISSUE TITLE
Container loot modifier button not working

### ISSUE THREAD

**Issue by Yeomans** [ForgottenGlory/Masterstroke#23]
**Masterstroke Version**
Beta 1.

**Describe the bug**
When looting various items from a container (books, food etc) the default action is "Take". You can hold the Shift modifier to change the action to "eat" or "read" etc, but doing this action still loots the item.

**To Reproduce**
Open container and try to eat food, or read book directly using the modifier key:

**Expected behavior**
The alternative action is performed.

**Comment by ForgottenGlory** [comment]
Not a bug, Better Container Controls changes how this works.
