### ISSUE TITLE
Freefly Cam bug

### ISSUE THREAD

**Issue by Yeomans** [ForgottenGlory/Masterstroke#24]
**Masterstroke Version**
Beta 1.

**Describe the bug**
When starting an SL scene the switch to FreeFlyCam sometimes bugs out to varying degree.
I've had it flip upside down quite often.
In one case it teleported the camera underground, or something.

**To Reproduce**
Start SL scene.

**Expected behavior**
Camera oriented correctly and positioned nearby player.

**Screenshots**
![image](https://user-images.githubusercontent.com/22068629/155876971-ffc67a5f-4de0-4a31-be69-fda254ffc943.png)

**Comment by ForgottenGlory** [comment]
This is a thing that can happen with FFC and SmoothCam, unsure of if there's a fix. Will fix when a fix is found.
