### ISSUE TITLE
TAWOBA books not readable/missing

### ISSUE THREAD

**Issue by Banzaibear** [ForgottenGlory/Masterstroke#25]
**Masterstroke Version**

Beta 1

**Describe the bug**

The mythic volumes that unlock the bikini armours are not readable (or missing in the case of Embershard Mine). I can console them in, but cannot actually use them in the worldspace. 

**To Reproduce**
Checked hide and iron books, Hide was there, not usable. Could not find iron where it normally spawns. 

**Expected behavior**
Need books to be clickable so you can learn recipes. This bug was reported on the forums for The Amazing World of Bikini Armor Balanced and Renamed in January, but the author thought they fixed it.

**Comment by ForgottenGlory** [comment]
Not a bug, they're not usable. You just need them in your inventory. TAWOBAR changes the locations for some of them.
