### ISSUE TITLE
Invisible Vampire Armor and Mage robes

### ISSUE THREAD

**Issue by MaiNeym** [ForgottenGlory/Masterstroke#26]
**Masterstroke Version**
Beta 1

**Describe the bug**
Some female armors appear to be invisible:

- Vampire Armor (ID: **020191F3**)  
You start with this if you picked the alternate start: "I'm part of a vampire clan"  
A different variant on the NPCs I saw works fine (ID: 020142C7)  
- Apprentice robes of Alteration (ID: **0010D66C**), 
Apprentice robes of Restoration (ID:  **0010E2DB**), 
Master robes of Destruction (ID:  **0010D678**), 
_and probably other mage robes..._ 
Several female NPCs in college of winterhold wearing these robes have an invisible torso.

**To Reproduce**
Wear the Vampire armor by starting the alternate start: "I'm part of a vampire clan"
Or visit the college of winterhold and watch the female NPCs

**Expected behavior**
No invisible armor

**Screenshots**
![image](https://user-images.githubusercontent.com/35378646/155884711-f639e84f-8884-4f07-b40d-a32be1280d94.png)
![image](https://user-images.githubusercontent.com/35378646/155885045-2fac8343-3606-4b76-a83d-eed5588fd0af.png)
![image](https://user-images.githubusercontent.com/35378646/155898476-991a0e2c-9d2c-4cc9-95b4-8790c8e8f9e9.png)

**Additional context**
I did not use the bodyslide tool. And changing body with OBody ingame doesn't fix it.  
The other few armors I found so far work correctly.

**Comment by ForgottenGlory** [comment]
Are you using the skimpy bodyslides or the regular ones?

**Comment by ForgottenGlory** [comment]
Either way, should be fixed Beta 2

**Comment by MaiNeym** [comment]
This was without the skimpy option enabled.  
A quick look with the skimpy bodyslides enabled seemed to be fine.

Thanks for the fast fixes.
