### ISSUE TITLE
Shor's Stone Milk Pump is levitating -galg001-

### ISSUE THREAD

**Issue by AgileCactus27** [ForgottenGlory/Masterstroke#27]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[Masterstroke Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Masterstroke Version**
Beta 1 - 1st public installer version

**Describe the bug**
The milk pump in Shor's Stone is levitating above the ground.

**To Reproduce**
Steps to reproduce the behavior: Go there lol

**Expected behavior**

**Screenshots**
![enb2022_2_27_16_06_41](https://user-images.githubusercontent.com/100524971/155888508-67e815a1-fb4c-464a-af6c-9d9e95974fe7.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
Should be fixed Beta 3
