### ISSUE TITLE
drugs in Riften skooma whore den aren't considered contraband before picking up -galg003-

### ISSUE THREAD

**Issue by AgileCactus27** [ForgottenGlory/Masterstroke#29]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[Masterstroke Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Masterstroke Version**
Beta 1 - 1st public installer version

**Describe the bug**
Drugs laying around in the Riften skooma den aren't considered contraband, until i pick em up, since Skooma Whore marks all drugs as contraband as long as they're in the inventory. dunno if this is an actual issue. i also don't know if this is the case in the other skooma dens

**To Reproduce**
go to Riften skooma den, have a look at the drugs behind the vendor. the door was open.

**Expected behavior**

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
Not a bug, just a quirk with how Skooma Whore works.
