### ISSUE TITLE
A pose for furniture animations

### ISSUE THREAD

**Issue by zarantha** [ForgottenGlory/Masterstroke#3]
**Masterstroke Version**
alpha 4

**Describe the bug**
when playing furniture animations, sometimes the npc and pc will A pose. 
this can happen when starting out, or when changing animations
does not seem limited to one animation pack

**To Reproduce**
set furniture animations chances to max in the furniture sex mcm
(override chance to 1.00, override bed chance to 1.00)
have sex with an npc near furniture, and have a furniture animation selected
enabling sexlab debug may help with confirming what animation is selected

**Expected behavior**
no A posing

**Additional context**
I have serious trouble rerunning Nemesis, so take this with a grain of salt i guess.
Rerunning Nemesis does not fix the issue.
I was unable to test FNIS + Nemesis due to issues running Nemesis
Removed Nemesis mods
     Project New Reign - Nemesis Unlimited Behavior Engine
     XPMSSE - Nemesis - Papyrus Stack Fix
     Nemesis - Generated Output
Installed FNIS and ran it
I am not seeing A pose during furniture sex animations anymore. 
If done on an existing game, the NPCs will be A posed until the move/reset their current animation, then they seem good.
Expect that issue will go away with a new game that never had nemesis.

**Comment by ForgottenGlory** [comment]
Fixed Pre-Alpha 5
