### ISSUE TITLE
heavy attack while blocking slows the game -galg004-

### ISSUE THREAD

**Issue by AgileCactus27** [ForgottenGlory/Masterstroke#30]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[Masterstroke Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Masterstroke Version**
Beta 1 - 1st public installer version

**Describe the bug**
when i block with a shield and press Mouse 3 (heavy attack) the game slows down, like when i'm under the effect of skooma. unfortunately this effect didn't end. i waited around 40-60 seconds. entering the menu and going back to the game fixed this for me. the activbe effects tab didn't show anything related to this.

**To Reproduce**
SAVE ATTACHED
load, block + mouse 3
[saves.zip](https://github.com/ForgottenGlory/Masterstroke/files/8148930/saves.zip)

**Expected behavior**

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by AgileCactus27** [comment]
edit after closing the game and trying again after loading the save:
now the slowmo effect only lasts as long as the shield bash. ¯\_(ツ)_/¯

**Comment by ForgottenGlory** [comment]
Not a bug, read Engarde
