### ISSUE TITLE
keybinds doesn't work in menus, storages, etc  -galg005-

### ISSUE THREAD

**Issue by AgileCactus27** [ForgottenGlory/Masterstroke#31]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[Masterstroke Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Masterstroke Version**
Beta 1 - 1st installer version

**Describe the bug**
keybinds doesn't work in menus. i always have to change keybinds, since i'm a lefty. i checked the masterstroke keymap and made sure, no key gets double-assigned.
Example: Action Key is Q, but in menus its still E. Sheathe is Mouse 4, in menus "sheathe" becomes "Take all". but Take all is still R.

**To Reproduce**
Steps to reproduce the behavior: change Skyrim keybinds.

**Expected behavior**
keybinds should apply to any storages, dialogues, menus and pop-up messages

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
Not a bug, read Better Container Controls
