### ISSUE TITLE
Millwater Retreat - lantern stuck in tree -galg006-

### ISSUE THREAD

**Issue by AgileCactus27** [ForgottenGlory/Masterstroke#32]
**Masterstroke Version**
BETA 1 - 1st installer version

**Describe the bug**
there is a lantern at millwater retreat thats stuck in a big tree

**To Reproduce**

**Expected behavior**

**Screenshots**
![enb2022_2_27_17_41_08](https://user-images.githubusercontent.com/100524971/155891357-1cb4b6c9-84b4-4e4a-9883-14ab0f617897.png)

**Comment by ForgottenGlory** [comment]
Need a screenshot of the object in question selected in console

**Comment by AgileCactus27** [comment]
Here's the tree:
![enb2022_3_2_23_08_07](https://user-images.githubusercontent.com/100524971/156458158-64d9b276-2dee-4e27-a65a-935351cac668.png)


And here's the lamp post:
![enb2022_3_2_23_09_40](https://user-images.githubusercontent.com/100524971/156458193-44d03edc-1334-4eb0-bc2e-6d3e321a7a88.png)
![enb2022_3_2_23_09_41](https://user-images.githubusercontent.com/100524971/156458221-0ad9f3ff-81de-412a-861d-010659033570.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
