### ISSUE TITLE
Millwater Retreat again - small tent clipping into house wall -galg007-

### ISSUE THREAD

**Issue by AgileCactus27** [ForgottenGlory/Masterstroke#33]
**Masterstroke Version**
BETA 1 - 1st public installer version

**Describe the bug**
at millwater retreat there is a house next to the forge. a tent from vanilla skyrim is clipping into one of the walls of said house.

**To Reproduce**

**Expected behavior**

**Screenshots**
![enb2022_2_27_18_04_44](https://user-images.githubusercontent.com/100524971/155892162-bc87d19f-03ba-49d5-8ccc-cee6cadcc4ef.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
