### ISSUE TITLE
Perk title text in the perk selection screen is misaligned.

### ISSUE THREAD

**Issue by catapsis** [ForgottenGlory/Masterstroke#34]
**Masterstroke Version**
Beta 1

**Describe the bug**
In the perk selection screen, when viewing a perk tree, the perk title text is not properly aligned with the perk stars, instead being offset quite a bit to the left.

**To Reproduce**
In the perk selection screen, select/zoom into one of the perk trees. Observe how the perk title text is offset to the left.

**Expected behavior**
The perk titles should be hovering just above the perk star they belong to.

**Screenshots**
![enb2022_2_27_10_14_10](https://user-images.githubusercontent.com/62223653/155892602-2830763f-3640-4094-94f1-ad7c84fbc522.jpg)

**Additional context**
I'm using the optional 21:9 UI mod.

**Comment by ForgottenGlory** [comment]
Related to #_5

**Comment by ForgottenGlory** [comment]
Related to #5
