### ISSUE TITLE
Falkreath Grave Concoctions double shop sign -galg008-

### ISSUE THREAD

**Issue by AgileCactus27** [ForgottenGlory/Masterstroke#35]
**Masterstroke Version**
BETA 1 - 1st public installer version

**Describe the bug**
Grave Concoctions in Falkreath has two shop signs in the same place (screenshot)

**To Reproduce**

**Expected behavior**

**Screenshots**
![enb2022_2_27_19_19_11](https://user-images.githubusercontent.com/100524971/155894674-d65a8709-2eaa-42b9-9123-ee20134c787d.png)

**Comment by ForgottenGlory** [comment]
Can you get a screenshot with the other sign selected in console please?

**Comment by AgileCactus27** [comment]
![enb2022_3_2_23_06_37](https://user-images.githubusercontent.com/100524971/156457649-f0282414-20a7-4df1-b3ce-90ad152d4067.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
