### ISSUE TITLE
Longer text pop-ups are getting cut off and not showing the entire text block.

### ISSUE THREAD

**Issue by catapsis** [ForgottenGlory/Masterstroke#36]
**Masterstroke Version**
Beta 1

**Describe the bug**
When a descriptive text pop-up appears, longer text gets cut off.

**To Reproduce**
Generate a pop-up with sufficiently long text (e.g., prostitution punishment). 

**Expected behavior**
The entire block of text should be visible.

**Screenshots**
![enb2022_2_27_11_45_31](https://user-images.githubusercontent.com/62223653/155895965-26462770-93ad-409a-9bf5-ed528ace2bee.jpg)

**Additional context**
The 21:9 optional UI mod was enabled.

**Comment by ForgottenGlory** [comment]
Related to #5
