### ISSUE TITLE
After punishment, returned inventory is incorrectly marked as stolen.

### ISSUE THREAD

**Issue by catapsis** [ForgottenGlory/Masterstroke#37]
**Masterstroke Version**
Beta 1

**Describe the bug**
When punished for insufficient money made from prostitution (in Whiterun, but this could apply elsewhere), player inventory is removed. When the inventory is returned afterwards, it is marked as stolen.

**To Reproduce**
Get in trouble for not turning in enough money after prostitution while having items. Check the theft status of the items before and after the punishment.

**Expected behavior**
Items that haven't been stolen should be returned to the player without being marked as stolen.

**Screenshots**
Before inventory removal:
![Before](https://user-images.githubusercontent.com/62223653/155896266-1eb6d6d8-f54c-4f56-92a0-ddb4dbb6f42f.jpg)

After inventory return:
![After](https://user-images.githubusercontent.com/62223653/155896286-23f430e6-7aa5-4321-927d-b544a023e2e0.jpg)

**Additional context**
The optional 21:9 UI mod is enabled.

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
