### ISSUE TITLE
Glowing Armor in Jorrvaskr 

### ISSUE THREAD

**Issue by ChrisJones75** [ForgottenGlory/Masterstroke#39]
**Masterstroke Version**
Beta1

**Describe the bug**
Weird edge lighting on certain armor and clothing in the Jorrvaskr main hall. Only happens when the camera is facing the back doors, regardless of character orientation.

**To Reproduce**
Enter Jorrvaskr in iron armor.

**Expected behavior**
No glowing edges on clothing and armor.

**Screenshots**

![Skyrim Special Edition 2_27_2022 2_33_59 PM](https://user-images.githubusercontent.com/8865797/155897184-5b3f87f6-f2c4-45f3-8e95-f9bac222c6ca.png)
![Skyrim Special Edition 2_27_2022 2_34_09 PM](https://user-images.githubusercontent.com/8865797/155897188-dcd7bcb4-b7ee-437b-b85c-42b3c058230e.png)
![Skyrim Special Edition 2_27_2022 2_34_25 PM](https://user-images.githubusercontent.com/8865797/155897190-1bb11887-caef-42b0-939f-65c4efe6d620.png)
![Skyrim Special Edition 2_27_2022 2_34_30 PM](https://user-images.githubusercontent.com/8865797/155897193-38e7de50-f085-4658-996f-4c64d79bed93.png)
![Skyrim Special Edition 2_27_2022 2_34_48 PM](https://user-images.githubusercontent.com/8865797/155897197-ee0f2b95-ca23-4476-a9be-3327bbd23335.png)
![Skyrim Special Edition 2_27_2022 2_34_54 PM](https://user-images.githubusercontent.com/8865797/155897202-a08a772d-86bc-4864-956f-84edea151ded.png)
![Skyrim Special Edition 2_27_2022 2_35_21 PM](https://user-images.githubusercontent.com/8865797/155897208-0d6cd91b-b6ca-45d8-ad59-100877e02334.png)

**Additional context**
Selected to start as a Companion using the Alternate Perspective menu.

**Comment by ForgottenGlory** [comment]
Should be fixed Beta 2
