### ISSUE TITLE
Training menu UI is cut off in 21:9 aspect ratio.

### ISSUE THREAD

**Issue by catapsis** [ForgottenGlory/Masterstroke#40]
**Masterstroke Version**
Beta 1

**Describe the bug**
The skill training UI panel is too low on the screen, causing the bottom of it to be cut off. This is in 21:9 aspect ratio; I'm uncertain that it affects the 16:9 version.

**To Reproduce**
Enable the 21:9 UI mod and attempt to train a skill from a skill trainer. Observe the misplacement of the training dialogue.

**Expected behavior**
Training UI should be entirely visible.

**Screenshots**
![enb2022_2_27_12_25_12](https://user-images.githubusercontent.com/62223653/155898259-58f0e4b5-e792-465a-a2c2-65e1a99886ab.jpg)

**Additional context**
Using 21:9 optional UI mod.

**Comment by ForgottenGlory** [comment]
Related to #5
