### ISSUE TITLE
Toys notification text is conflicting with the HUD UI elements.

### ISSUE THREAD

**Issue by catapsis** [ForgottenGlory/Masterstroke#42]
**Masterstroke Version**
Beta 1

**Describe the bug**
The toys notification text is behind the UHD UI.

**To Reproduce**
Get affected by a toy that generates the appropriate text. Observe the location of the text behind the UI.

**Expected behavior**
Game text should be readable and not be behind UI elements.

**Screenshots**
![enb2022_2_27_20_26_11](https://user-images.githubusercontent.com/62223653/155922925-17c98f8f-7e01-486a-9d0a-4e529c0c01e5.jpg)

**Comment by ForgottenGlory** [comment]
You're using the Ultrawide patch, correct? These messages should be appearing in the top left of the screen.

**Comment by ForgottenGlory** [comment]
Should be fixed Beta 2
