### ISSUE TITLE
OBody changes impact clothes but not npc bodies

### ISSUE THREAD

**Issue by xBL4CKB34RDx** [ForgottenGlory/Masterstroke#45]
**Masterstroke Version**
Beta 1

**Describe the bug**
When using OBody to adjust body type to preference, NPC bodies remain the same (only gear is adjusted). I noticed that when the same NPC is turned into a milkmaid, her body will change temporarily for milking animations but revert back afterwards.

**To Reproduce**
Followed install and setup directions, then use OBody command "U" to adjust body type.

**Expected behavior**
NPC body should change alongside gear position changes.

**Screenshots**
Location of screenshot noted in Skyrim is not correct (i.e. screenshots not present). If I am able to find them or find another way to capture, I will come back and attach them.

**Comment by catapsis** [comment]
Screenshots created via the Print Screen button should be in your "Masterstroke\Stock Game\" folder.

**Comment by xBL4CKB34RDx** [comment]
Thank you very much for pointing this out! I have provided a link to the screenshot which illustrates the issue. You can see on the NPC Recorder the nipple piercings are lower than where her nipples are (also general clipping of "bitch boots" is obvious) and I put in red arrows to point out the nipple piercings on Cerri since they weren't as obvious but show how her breasts should be farther out (she's rather flat right now).

https://imgur.com/nIWdyaq

**Comment by xBL4CKB34RDx** [comment]
Also, worth mentioning... while another user pointed out the gags are not aligned, you can see here that I'm experiencing the same thing. Further, maybe due to the misalignment, mouths aren't open either. Happy to open a separate bug for the gag issue if I'm recalling incorrectly and its needed.

**Comment by ForgottenGlory** [comment]
Recorder should be fixed with Beta 2, looking into a fix for Cerri. Basically these NPCs in particular use custom bodies so OBody doesn't know what to do with them. Please continue to report these as they come up.

**Comment by xBL4CKB34RDx** [comment]
Will do! Just wanted to add that I think you and the dev team have done amazing work so far... Thank you.
