### ISSUE TITLE
Xander - Winking Skeever - missing mesh hair -galg009-

### ISSUE THREAD

**Issue by AgileCactus27** [ForgottenGlory/Masterstroke#46]
**Masterstroke Version**
BETA 1 - 1st public installer version

**Describe the bug**
That guy Xander in the Winking Skeever has shiny missing mesh hair.

**To Reproduce**

**Expected behavior**
Nice'n shiny hair

**Screenshots**
![enb2022_2_28_21_16_45](https://user-images.githubusercontent.com/100524971/156052887-914c82d1-d18b-4e7d-81c1-b9c39a867ba6.png)
![enb2022_2_28_21_19_47](https://user-images.githubusercontent.com/100524971/156052912-0a435009-b2bc-421c-a87c-09c18cad4832.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
