### ISSUE TITLE
Panties may be using torso slot 

### ISSUE THREAD

**Issue by 7r4dic7** [ForgottenGlory/Masterstroke#47]
**Masterstroke Version**
Beta 1

**Describe the bug**
Panties behaves like torso armor.

**To Reproduce**
Just equip a panty .

**Expected behavior**
Pantys should be treated as an accessory and not like the torso piece.

**Comment by sgtsnicker** [comment]
One of the intrigue satchels also bug out like that and take the place of a torso item.
