### ISSUE TITLE
Functions sharing the same binding by default blocks some functionality

### ISSUE THREAD

**Issue by thatoneguy404** [ForgottenGlory/Masterstroke#48]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[Masterstroke Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Masterstroke Version**
Beta 1

**Describe the bug**
The original issue was that I thought compass didnt work so I reinstalled the list, upon further looking I found that the issue was Immersive hud and its toggle on keybind. It is currently bound to X, open journal and quicklight is also bound to this same key. Rebinding Immersive Hud fixes this issue. I also changed the compass transparency from 0 to 100 inside of the Immersive Hud MCM(though im unsure if this was even necessary) Also by default the Immersive Hud is not set to toggle off/on which would mean you would have to hold it down

**To Reproduce**
1: Obtain Compass
2: Press X 
3: Journal opens(forcing you to exit out of it manually), quicklight activates, compass activates for a brief moment but by the time you close journal is gone.

**Expected behavior**
Press Immersive Hud toggle key and compass displays

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
Related to #15
