### ISSUE TITLE
Item duplication glitch caused by companion Recorder and the outfit manager.

### ISSUE THREAD

**Issue by catapsis** [ForgottenGlory/Masterstroke#49]
**Masterstroke Version**
 Beta 1

**Describe the bug**
Using the companion outfit manager on Recorder allows for the duplication of any wearable items (weapons and armor/accessories).

**To Reproduce**
1. Get Recorder as a companion. I tested it with Cerri Steelfist as well, but it didn't seem to work for her. Might be a glitch exclusive to Recorder.
2. Use the "Let me manage your outfit. -> Pick outfit," dialogue to open the companion outfit inventory.
3. Give Recorder whatever equipment you want to duplicate as her outfit.
4. Close out and let her equip the outfit.
5. Enter her inventory and take all of the items.
6. Use the "Let me manage your outfit. -> Pick outfit," dialogue again. Observe that the items are still there.
7. Repeat from step 4 to generate unlimited item duplicates.

**Expected behavior**
The outfit manager shouldn't be duplicating items.

**Screenshots**
![enb2022_2_28_17_31_22](https://user-images.githubusercontent.com/62223653/156082086-36549fb4-4c17-48ae-aa0d-254e6d15a7cf.jpg)
Duplications can be seen by the items that have x5.
Recorder's Info:
![enb2022_2_28_17_54_51](https://user-images.githubusercontent.com/62223653/156084220-5f7e1654-f8f3-4ce3-9b78-a77aef884287.jpg)

**Comment by ForgottenGlory** [comment]
Will fix when a fix is found
