### ISSUE TITLE
UI: misalignment after mcm setup, at least on ultrawidescreen

### ISSUE THREAD

**Issue by dervishxgit** [ForgottenGlory/Masterstroke#5]
The ui widgets do not correctly align after mcm setup, on ultrawide.

My only guess here is that perhaps some widgets are using a relative (percent) position value and the one out place is using an absolute (pixel) value?

I'll post a screen on the discord channel.

**Comment by catapsis** [comment]
To add on to this, I'd suggest that, when addressing this problem, the UI elements be kept in their 16:9 locations rather than pushing them all the way to the screen edge. Having them too far off to the side makes them difficult to reference.

**Comment by ForgottenGlory** [comment]
Should be fixed Beta 2
