### ISSUE TITLE
Changed values for Exhausted/Weakness Thresholds in Scrappies Matchmaker's MCM don't register

### ISSUE THREAD

**Issue by Maelstrom8** [ForgottenGlory/Masterstroke#51]
**Masterstroke Version**
Beta 1

**Describe the bug**
When you change the Health, Stamina and or Magicka Threshold under Profile subcategory of Scrappies Matchmaker MCM and then when you either re-look at it or click on another subcategory, they reset - as if they were never set.

**To Reproduce**
Step 1: Open MCM options for Scrappies Matchmaker
Step 2: Go to Profile
Step 3: Change any of the three thresholds (Health/Stamina/Magicka) to above 0, hit enter 
Step 4: Click on any subsection (eg Location), click on the option again or go to advanced method and back out, it will reset to 0
Note: if you put it to 100%, it'll switch to 1%. 0-99 results in it not being registered

**Expected behavior**
Well, they're supposed to register what you put. It almost seems like it behaves weirdly like a fixed value instead of percentage and only accepts "1.0"

Video:
https://www.youtube.com/watch?v=q-y_xEBiqx0

**Comment by ForgottenGlory** [comment]
Did you actually select a profile? This part of the MCM doesn't do anything unless you pick a Profile to modify.

**Comment by Maelstrom8** [comment]
> Did you actually select a profile? This part of the MCM doesn't do anything unless you pick a Profile to modify.

Yes, I selected 'Add Profile", named it "Custom - Maelstrom". Sorry, forgot to include the full screenshot: https://i.imgur.com/vX0UQr0.png

Not sure if I'm missing anything.

**Comment by ForgottenGlory** [comment]
Will fix when fix is found, looks like Scrab is working on an update to this mod so hopefully that will resolve it.
