### ISSUE TITLE
Public Whore - invisible weapon equipped - guards go nuts -galg010-

### ISSUE THREAD

**Issue by AgileCactus27** [ForgottenGlory/Masterstroke#52]
**Masterstroke Version**
BETA 1 - 1st public installer version

**Describe the bug**
i got at problem with public whore. when made the public whore by the introduction quest in solitude, guards are constantly admonishing me for carrying weapons. after that, a nameless and invisible item is automatically unequipped (i get a notification at this point). a few seconds later, the next guard is already coming my way

**To Reproduce**
Steps to reproduce the behavior: load the save, talk to Vedia Belenus, talk to jarl Elisif, have fun doing everything wrong, just like a married man.

**Screenshots**
[saves.zip](https://github.com/ForgottenGlory/Masterstroke/files/8163581/saves.zip)

**Additional context**
At least two other users from the discord hat this problem in other places too.

**Comment by ForgottenGlory** [comment]
Fixed Beta 2
