### ISSUE TITLE
Physics glitch during/after scene with Toys transformation

### ISSUE THREAD

**Issue by CaseyAnthonyWeiner** [ForgottenGlory/Masterstroke#53]
**Masterstroke Version**
0.1.0 beta

**Describe the bug**
During a scene (or after, possibly) while you have transformable toys equipped, it seems to cause SMP physics to glitch out. I have a save game right before a scene with Nelacar which should allow it to be reproduced pretty easily. I've had it happen immediately after the transformation, and sometimes a few seconds after when the scene changes stages.

**To Reproduce**
Begin the encounter with Nelacar by talking to him and choosing "Umm..."

**Expected behavior**
No physics weirdness.

I'm not sure if these are the only items that can cause this, but this is the one equipped. (the exotic version)

![image](https://user-images.githubusercontent.com/69488425/156229716-6b957096-02f3-4959-98ab-8872518e85a7.png)

** Save files **
[saves.zip](https://github.com/ForgottenGlory/Masterstroke/files/8164053/saves.zip)

**Comment by ForgottenGlory** [comment]
Will fix when a fix is found
