### ISSUE TITLE
Dark Knight sword and armor set are invisible

### ISSUE THREAD

**Issue by vdog218** [ForgottenGlory/Masterstroke#54]
**Masterstroke Version**
0.1.0 beta

**Describe the bug**
When crafting the dark knight armor or sword in the forge they are invisible.

**To Reproduce**
go to any blacksmith forge and craft any item from the dark knight set
**Expected behavior**
visible weapons and armor from the dark knight set
**Screenshots**

![20220301222602_1](https://user-images.githubusercontent.com/100744110/156289605-4afe6b2a-b151-44a7-9bf9-eda948f64da9.jpg)
![20220301222610_1](https://user-images.githubusercontent.com/100744110/156289612-edfef9f1-dbe1-4b18-bf83-f22b1bab926b.jpg)

**Comment by ForgottenGlory** [comment]
Should be fixed Beta 2
