### ISSUE TITLE
Map issues still present

### ISSUE THREAD

**Issue by thatoneguy404** [ForgottenGlory/Masterstroke#55]
**Masterstroke Version**
Beta 2

**Describe the bug**
Map visual is bugged

**Screenshots**

![Untitled-2](https://user-images.githubusercontent.com/64243912/156481463-c03000c3-fd88-4a18-8b45-6eb699f4a7e0.png)
[Saves.zip](https://github.com/ForgottenGlory/Masterstroke/files/8174265/Saves.zip)

**Comment by ForgottenGlory** [comment]
fixed
