### ISSUE TITLE
Miri's Satchel is inside a tree near her start location

### ISSUE THREAD

**Issue by DLNight** [ForgottenGlory/Masterstroke#56]
Beta 2

Miri's Satchel is inside a tree near her start location.
![image](https://user-images.githubusercontent.com/100830558/156517114-019cc008-7735-4b85-8c44-df5514ce5015.png)

![image](https://user-images.githubusercontent.com/100830558/156516864-6cb2dca9-719b-489d-aa24-c8fe474fdc29.png)

**Comment by ForgottenGlory** [comment]
Need a screenshot with the tree selected in console
