### ISSUE TITLE
Multiple overlapping HUD Bars

### ISSUE THREAD

**Issue by DLNight** [ForgottenGlory/Masterstroke#57]
**Masterstroke Version**
Beta 2

**Describe the bug**
A secondary mana and stamina bar show up when they are not at 100%
![image](https://user-images.githubusercontent.com/100830558/156517391-58379797-8b3f-431f-9d07-e9eb55d55c3a.png)

**To Reproduce**
Shows up as soon as I cast

**Comment by lordkabal26** [comment]
The solution is to go into Immersive HUD and turn the transparency for Health, Magicka, and Stamina down to 0 to render the vanilla bars invisible. That might be something that could be recorded for Beta 3.

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
