### ISSUE TITLE
Hotkeys for SL Separate Orgasm conflict with camera control hotkeys

### ISSUE THREAD

**Issue by DLNight** [ForgottenGlory/Masterstroke#58]
**Masterstroke Version**
Beta 2

**Describe the bug**
The hotkeys for SL Separate Orgasm (M1 and M2) are also the hotkeys to move the camera during a Sexlab scene.

**To Reproduce**
Clicking M1 raises the camera and M2 lowers the camera. Also has the effect of BonusEnjoyment and Edge as well from SL Separate Orgasm I think.

**Expected behavior**
Hotkeys should be different so the camera doesn't move when using hotkeys for the minigame

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
