### ISSUE TITLE
Black face fella

### ISSUE THREAD

**Issue by LunaPapilio** [ForgottenGlory/Masterstroke#6]
![image](https://user-images.githubusercontent.com/77394294/150658580-3dc04db4-2c22-4dfd-82ca-5dbc135c253d.png)

Over in Windhelm, one of the refugees.

**Comment by LunaPapilio** [comment]
![image](https://user-images.githubusercontent.com/77394294/150658622-21b2f644-f4e1-412f-bc4e-8231e745f7f9.png)
Black face continues, also in windhelm, same area as the refugee.

**Comment by LunaPapilio** [comment]
![image](https://user-images.githubusercontent.com/77394294/150659464-0e26b0db-f556-43d5-90eb-33870a49507b.png)
Still in windhelm, still refugee area

**Comment by LunaPapilio** [comment]
![image](https://user-images.githubusercontent.com/77394294/150659973-3579f9ac-d9fe-4367-8565-a4809b111bb1.png)
still windhelm

**Comment by ForgottenGlory** [comment]
Fixed Alpha 2
