### ISSUE TITLE
Follower Recorder Skin Misaligned

### ISSUE THREAD

**Issue by yonderbeard** [ForgottenGlory/Masterstroke#60]
**Masterstroke Version**
Beta 2

**Describe the bug**
Recorder's skin appears misaligned around her nipples.

**To Reproduce**
Initiate dialog to make Recorder a follower
Choose Manage Outfit -> Pick Outfit -> Exit Menu

**Expected behavior**
Expected Skin texture to be aligned properly

**Screenshots**
Links provided due to NSFW nature
https://i.imgur.com/MEILhzW.jpg
https://i.imgur.com/XeTIgQy.jpg
https://i.imgur.com/S81DqQ6.jpg

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
