### ISSUE TITLE
Farkas Werewolf Model Invisible

### ISSUE THREAD

**Issue by Canoliee** [ForgottenGlory/Masterstroke#61]
**Masterstroke Version**
Beta 2

**Describe the bug**
Follow companions quest line, Farkas's werewolf model is just a floating penis

**To Reproduce**
Follow The Companions quest line up to Dustmans Cairn 

**Expected behavior**
Farkas's Werewolf entire model shows up

**Screenshots**

![20220303232017_1](https://user-images.githubusercontent.com/100593301/156700183-0b70b738-544e-4d1b-97c9-93b4ce96254b.jpg)

![20220303232041_1](https://user-images.githubusercontent.com/100593301/156700186-b2f0c73d-0290-40d3-8173-31646362a596.jpg)

![20220303232044_1](https://user-images.githubusercontent.com/100593301/156700187-7367dc9b-ae8e-4670-8546-0e985099b2f0.jpg)

![20220303232052_1](https://user-images.githubusercontent.com/100593301/156700188-6c64138f-f807-480f-a3ca-9d719ef612be.jpg)

![20220303232057_1](https://user-images.githubusercontent.com/100593301/156700191-18c7a05a-d7dd-4ac5-ac61-f3d2e6003c61.jpg)

![20220303232801_1](https://user-images.githubusercontent.com/100593301/156700192-a05cef61-6021-44a0-807f-b7f64477b3c3.jpg)

**Comment by ForgottenGlory** [comment]
Should be fixed Beta 3
