### ISSUE TITLE
TAWOBA books not working

### ISSUE THREAD

**Issue by Banzaibear** [ForgottenGlory/Masterstroke#63]
**Masterstroke Version**
Beta 2

**Describe the bug**
TAWOBA books are either invisible or visible, but in both cases cannot be interacted with

**To Reproduce**
Console shows the invisible book, and if you add the book to your inventory and drop it - it vanishes/remains invisible. You can make the items at the forge with the book in your inventory, but no way to get them. 

**Expected behavior**
Recipe books need to be picked up. 

**Screenshots**
Embershard mine - invisible manual on workbench

![image](https://user-images.githubusercontent.com/72049103/156902304-488589de-c79e-4684-b293-f14de03abfc4.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
