### ISSUE TITLE
No manes on horses

### ISSUE THREAD

**Issue by Pudding9066** [ForgottenGlory/Masterstroke#66]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[Masterstroke Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Masterstroke Version**
Beta 2

**Describe the bug**
None of the horse have manes

**To Reproduce**
Look at a horse

**Expected behavior**
The horses should have manes

**Screenshots**
https://i.imgur.com/f0q4Mz2.jpg

**Additional context**
n/a

**Comment by ForgottenGlory** [comment]
Will fix when fix is found
