### ISSUE TITLE
Sigurd still has underwear

### ISSUE THREAD

**Issue by Pudding9066** [ForgottenGlory/Masterstroke#68]
**Masterstroke Version**
Beta 2

**Describe the bug**
Sigurd in Whiterun still has an underwear mesh and texture.

**To Reproduce**
Get Sigurd naked.

**Expected behavior**
Should be nude, esp during scenes

**Screenshots**
https://i.imgur.com/J0MBPDs.jpg

**Additional context**
n/a

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
