### ISSUE TITLE
Aela's Shield

### ISSUE THREAD

**Issue by Pudding9066** [ForgottenGlory/Masterstroke#69]
**Masterstroke Version**
Beta 2

**Describe the bug**
Aela's shield is available for purchase from Eorland prior to joining the Companions.

**To Reproduce**
Trade with Eorland without being a member of the Companions.

**Expected behavior**
Her shield should not be available for purchase as it is part of an early Companions quest. 

**Screenshots**
https://i.imgur.com/WSficCo.png

**Additional context**
n/a

**Comment by ForgottenGlory** [comment]
Unsure what's going on here. Help wanted.
