### ISSUE TITLE
Change hotkeys, they're conflicting

### ISSUE THREAD

**Issue by LunaPapilio** [ForgottenGlory/Masterstroke#7]
Sexlab move actor left/right conflicts with Quick Mass Follower Commands Hotkey - Changed this to Home key
Move actor forward/backward conflicts with Quick Light - Changed this to End
Default Smoothcam preset hotkey conflicts with Auto-Run key - Didn't change the key, I changed the Preset instead because I don't like the default
sexlab open Animations conflicts with OBody - Changed this to Insert
gender bender conflicts with changing SMP to CPBC - changed this Page Up

this seems to be everything, i'll update if i find more but it seems to be everything

**Comment by ForgottenGlory** [comment]
Fixed for Alpha 3
