### ISSUE TITLE
Draff's hair has no texture

### ISSUE THREAD

**Issue by Pudding9066** [ForgottenGlory/Masterstroke#70]
**Masterstroke Version**
Beta 2

**Describe the bug**
Draff, in the Ratway, has hair with no texture

**To Reproduce**
Enter the Ratway on the canal side.

**Expected behavior**
Hair should have a texture

**Screenshots**
https://i.imgur.com/vjbI8Uc.png

**Additional context**
Was difficult to get the hair to show as purple because the entire room is mostly candlelit.

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
