### ISSUE TITLE
Billyy Chair Animations are tposed

### ISSUE THREAD

**Issue by Pudding9066** [ForgottenGlory/Masterstroke#72]
**Masterstroke Version**
Beta 2

**Describe the bug**
During a scene triggered by Yamete, all chair animations from Billyy were just t-poses for both actors.

**To Reproduce**
Try to force animations

**Expected behavior**
Not t-posing

**Screenshots**
https://i.imgur.com/vkeFxh7.png

**Additional context**
n/a

**Comment by ForgottenGlory** [comment]
Should be fixed Beta 3
