### ISSUE TITLE
College Arcanium ctd

### ISSUE THREAD

**Issue by Zeenis88** [ForgottenGlory/Masterstroke#77]
**Masterstroke Version**
Beta 2

**Describe the bug**
Crash to desktop

**To Reproduce**
Crash to desktop on screen transition to The Arcanium or shortly after entering. Made four attempts to enter: Three ctd, one completed transition with ctd shortly after. The one time I was able to load in there was a noticeable framerate drop when looking at the librarian at the desk.

**Expected behavior**
Not ctd

[Crash_2022_3_8_17-30-10.txt](https://github.com/ForgottenGlory/Masterstroke/files/8210293/Crash_2022_3_8_17-30-10.txt)
[Crash_2022_3_8_14-12-36.txt](https://github.com/ForgottenGlory/Masterstroke/files/8210294/Crash_2022_3_8_14-12-36.txt)
[Crash_2022_3_8_12-17-57.txt](https://github.com/ForgottenGlory/Masterstroke/files/8210295/Crash_2022_3_8_12-17-57.txt)
[Crash_2022_3_8_12-1-35.txt](https://github.com/ForgottenGlory/Masterstroke/files/8210296/Crash_2022_3_8_12-1-35.txt)

**Comment by ForgottenGlory** [comment]
By chance did you have Quick Light turned on when you were entering the Arcanaeum?
