### ISSUE TITLE
CTD if you equip Adventurer's Intrigue Satchel while having a locked chastity piercing

### ISSUE THREAD

**Issue by Vhostym** [ForgottenGlory/Masterstroke#78]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[Masterstroke Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

[Crash_2022_3_7_21-55-2.txt](https://github.com/ForgottenGlory/Masterstroke/files/8211206/Crash_2022_3_7_21-55-2.txt)

If possible, please also attach a copy of your most recent save before the issue occurred.**

[saves.zip](https://github.com/ForgottenGlory/Masterstroke/files/8211238/saves.zip)

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Masterstroke Version**
Beta v2

**Describe the bug**
When you have a locked chastity piercing, do not have the needed key to unlock, and equip an intrigue satchel (or at least the adventurer's intrigue satchel, enchanted) the game attempts to unlock the piercing and equip the satchel, fails, and crashes to desktop (CTD).

**To Reproduce**
Equip a locked chastity piercing (in my case the basic toys-chastity piercing), and attempt to equip an adventurer's intrigue satchel.

**Expected behavior**
Ideally the satchel should equip without issue, but an acceptable response would be to have it fail to equip because of the piercing taking up the same slot. It shouldn't CTD.

**Screenshots**

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by Vhostym** [comment]
Minor update: I hadn't realized at the time but I was running off of the first release of Beta 2 wabbajack installer, which I have since updated due to a map glitch it contained. I don't believe this should have an impact on the bug replicability, but am mentioning it on the off chance that it does.

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
