### ISSUE TITLE
XP32 needs to win male skeleton conficts for Racemenu genital sliders to work

### ISSUE THREAD

**Issue by zarantha** [ForgottenGlory/Masterstroke#8]
XP32 needs to override SOS on these files:

/meshes/actors/werewolfbeast/character assets/skeleton.nif
/meshes/actors/character/character assets/skeletonbeast.nif
/meshes/actors/character/character assets/skeleton.nif

Hide or delete works ok, if changing the load order is a problem.

**Comment by ForgottenGlory** [comment]
Fixed Alpha 2
