### ISSUE TITLE
No XP reward on arrow bleed kill

### ISSUE THREAD

**Issue by Insave** [ForgottenGlory/Masterstroke#81]
**Masterstroke Version**
Beta 2

**Describe the bug**
Upon killing an enemy with with a bleed effect caused by an arrow no character experience is awarded via the Experience mod.

**To Reproduce**
Equip a bow and arrow
Fire at an enemy until  they are low on health
Allow the bleed effect to finish off the enemy
Observe no +xp message 

**Expected behavior**
Kills caused by damage over time due to arrow bleeding award character experience through Experience mod.

**Screenshots**
https://imgur.com/a/O7QOgNT
(Practically no information to glean from the image)

**Additional context**
This may be part of vanilla Skyrim where damage over time effects do not award kills to the player.

**Comment by ForgottenGlory** [comment]
Will fix when a fix is found
