### ISSUE TITLE
A Tree near Windhelm has a blocky model

### ISSUE THREAD

**Issue by puucco** [ForgottenGlory/Masterstroke#82]
**Masterstroke Version**
Beta 2

**Describe the bug**
A tree at the last waterfall between Windhelm and Ange's Mill has a very out of place look.

**Screenshots**
[https://i.imgur.com/sgFUR3S.png](https://i.imgur.com/sgFUR3S.png)

**Comment by ForgottenGlory** [comment]
Need a screenshot of it selected in console

**Comment by puucco** [comment]
The tree with console.
[https://i.imgur.com/MdHlHBE.png](https://i.imgur.com/MdHlHBE.png)
