### ISSUE TITLE
RyanReos Dark Elf Blader items are too valuable

### ISSUE THREAD

**Issue by puucco** [ForgottenGlory/Masterstroke#84]
**Masterstroke Version**
Beta 2

**Describe the bug**
The items added to Tanning Rack are too valuable for the crafting cost of 2 leather. 

**To Reproduce**
Interact with Tanning Rack and sort by value.

**Expected behavior**
The expected value for crafting recipe of 2 leathers should be 100-200g.

**Screenshots**
[Tanning Rack](https://i.imgur.com/eKx38ms.png)
[The Mod](https://i.imgur.com/0MxUhAr.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
