### ISSUE TITLE
Starting the main quest with Alternate Perspective breaks some UI elements

### ISSUE THREAD

**Issue by puucco** [ForgottenGlory/Masterstroke#85]
**Masterstroke Version**
Beta 2

**Describe the bug**
After Alduins first attack in Helgen, the mod hides your HUD to display title card, but it fails to restore all the UI elements. The things not coming back are the new health, magicka and stamina bars, True Directional Movement target lock reticule and floating health bars.

**To Reproduce**
Talk to the Helgen Inn Keeper and pick the start main quest option. Sleep in the bed, go outside and wait for the event to play out.

**Screenshots**
[The new status hud missing.](https://i.imgur.com/kqY1gKu.png)

**Comment by zarantha** [comment]
Also reported in the Bugs section for both AP and TrueHUD. 
HUD disappears just before the skyrim logo in the intro (after alduin shouts and before heading into the tower)
Nothing logged in papyrus, but I can get the log if you want.

Closing and relaunching the game fixed this for me. Did this just before looting gunjar in the keep.
Ran through it again and exiting the game/reloading in the tower (before you head upstairs and alduin breaks the wall) also works to restore the player widget.

Toggling TrueHUD in game did nothing.
