### ISSUE TITLE
Solitude Clockwork Terminus has a hole in the wall

### ISSUE THREAD

**Issue by puucco** [ForgottenGlory/Masterstroke#86]
**Masterstroke Version**
Beta 2

**Describe the bug**
Solitude Clockwork Terminus has a hole in the wall and the wall that should be there is in front of the portal gate. Falling in to the void teleports you behind the gate and you can continue despite the pillar blocking the gate. Also there is no collision check from behind the pillar so you can get out quite easily.

**To Reproduce**
Enter the Solitude Clockwerk Terminus near the Solitude Main Gate and observe.

**Screenshots**
[https://i.imgur.com/kASIT8f.png](https://i.imgur.com/kASIT8f.png)

**Comment by ForgottenGlory** [comment]
I don't see anything that would be causing this. Will fix when a fix is found.
