### ISSUE TITLE
Apprentice robes are invisible

### ISSUE THREAD

**Issue by zarantha** [ForgottenGlory/Masterstroke#87]
Masterstroke beta2

Looks like she should be using MageApprenticeRobesF which I do see in the core bodyslides. Not sure what's up with them.

![enb2022_3_13_18_29_05](https://user-images.githubusercontent.com/31942539/158082419-07a8a48b-729f-4e73-b829-840a146ac927.png)

**Comment by zarantha** [comment]
![enb2022_3_13_19_33_51](https://user-images.githubusercontent.com/31942539/158084284-c2db72b9-65a6-4d41-a45b-6491e9ea2db2.png)

**Comment by zarantha** [comment]
Rebuilding the bodyslides doesn't work.

BD's is overwriting, and i'm not using the skimpy replacers. Is BD's supposed to have a 2 in the file name? removing that fixed the robes for both outfits (apprentice and the journeyman that the master destruction robes point to). Do I even need the BD's esp if i'm not doing skimpy armors?

![image](https://user-images.githubusercontent.com/31942539/158084993-c66ad6bd-61ad-47cb-a27e-e9816d6cf88d.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
