### ISSUE TITLE
Lockpicking training and book level up levels Hand to Hand

### ISSUE THREAD

**Issue by Pudding9066** [ForgottenGlory/Masterstroke#88]
**Masterstroke Version**
Beta 2

**Describe the bug**
Reading a book that is supposed to level Lockpicking actually levels Hand to Hand, and asking for Lockpicking training also levels the Hand to Hand skill.

**To Reproduce**
Read a Lockpicking book or ask for Lockpicking training. 

**Expected behavior**
The training should level Security, but as the Hand to Hand tree replaced Lockpicking, there's no in-game way to get training.

**Screenshots**
https://i.imgur.com/2mwkZ5Q.png

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
