### ISSUE TITLE
Extended stay inn pricing cheaper than single night

### ISSUE THREAD

**Issue by Insave** [ForgottenGlory/Masterstroke#89]
**Masterstroke Version**
Beta 2

**Describe the bug**
Inn pricing heavily favors paying for extended stays over a single night.
Whiterun inn: The Bannered Mare through Helda
One night price: 100g
3 nights: 30g
1 week: 70g
1 month: 300g

**To Reproduce**
Talk to an inn keeper (Helda) to start dialog
Observe single night price in the initial dialog
Observe extended night pricing through the "I'd like to book an extended stay"

**Expected behavior**
Pricing of a single night vs extended nights to increase by a linear amount.

**Screenshots**
![singleNight](https://user-images.githubusercontent.com/6333841/158911728-aae14b67-7c51-4e8a-8bed-6ac98b16bdd8.png)
![extendedStay](https://user-images.githubusercontent.com/6333841/158911734-addb9980-5a39-488b-8a36-8bda1166da88.png)

**Comment by ForgottenGlory** [comment]
Fixed Beta 3
