### ISSUE TITLE
Wall remnants inside Breezehome

### ISSUE THREAD

**Issue by Eikonoklaste** [ForgottenGlory/Masterstroke#9]
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[Masterstroke Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Masterstroke Version**
Alpha1

**Describe the bug**
There's a one-way wall in Breezehome that appears to be from Lux. It's one-way because the mesh only shows when looking in on direction (pictured).

**To Reproduce**
Enter Breezehome and approach the stairs from the left side of the central bookcase, the wall will be to your right. Trying to view from the right side will result in seeing nothing.

**Expected behavior**
No extra walls in my house.

**Screenshots**
![enb2022_1_25_15_05_56](https://user-images.githubusercontent.com/85655234/151051953-f0b3632e-a63a-4707-9851-3d6b9cd1d70f.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**

**Comment by ForgottenGlory** [comment]
Fixed alpha 2
