### ISSUE TITLE
Wabbajack installation problems

### ISSUE THREAD

**Issue by krkoor** [ForgottenGlory/Masterstroke#91]
**Masterstroke Version**
Beta 2

**Describe the bug**
Hello 
There is an issue with the wabbajack installation, it gives the following errors at the very end of the installation process.
48.82 - Found 868 total files, 860 matching filesize
48.92 - Unable to download SE.rar (HTTPDownloader+State|https://mega.nz/folder/xwxwzaDI#J3oxuELfc50dftUKQiIcUg/file/csZHUKrY)
48.92 - Unable to download Skooma Whore Patch V1.03 SE.7z (LoversLabOAuthDownloader+State|2229|Skooma Whore Patch V1.03 SE.7z|False)
48.92 - Unable to download SLSW Addicted 3.635 SE.7z (LoversLabOAuthDownloader+State|2229|SLSW Addicted 3.635 SE.7z|False)
48.92 - Unable to download Community Overlays 1 - CBBE Male and Female Repackage.zip (GoogleDriveDownloader+State|1DMWc4kzWRm-Cwtn3EAmIiRo7p1bJmx15)
48.92 - Cannot continue, was unable to download one or more archives

The issue with SE.rar can be fixed with a manual download from the link, however for Skooma and SLSW, new versions of those mods dropped very recently so the current list doesn't work. As for the Community Overlays mod I have no idea what is wrong with it.

**Screenshots**
![image](https://user-images.githubusercontent.com/101931199/159121290-afd48f61-2585-4108-9ce2-14a7f4e01734.png)

Sorry for the inconvenience 
Thanks

**Comment by ForgottenGlory** [comment]
k
