### ISSUE TITLE
Missing archives, Installation Failed.

### ISSUE THREAD

**Issue by ghost** [ForgottenGlory/Masterstroke#92]
I am reporting an installation bug where certain files are failing to download. Additionally, I was not able to find one of the specific files mentioned, "Community Overlays 1", although I must confess that I have not searched for it ad nauseam.

**Masterstroke Version**
Beta 2 (?) - latest as of yesterday, 19/03/22, when I began my installation.

**Describe the bug**
A few archives are failing to download. I am attaching a log file for reference.

To quote directly from it:
11,54 - Unable to download SE.rar (HTTPDownloader+State|https://mega.nz/folder/xwxwzaDI#J3oxuELfc50dftUKQiIcUg/file/csZHUKrY)
11,54 - Unable to download Skooma Whore Patch V1.03 SE.7z (LoversLabOAuthDownloader+State|2229|Skooma Whore Patch V1.03 SE.7z|False)
11,54 - Unable to download SLSW Addicted 3.635 SE.7z (LoversLabOAuthDownloader+State|2229|SLSW Addicted 3.635 SE.7z|False)
11,54 - Unable to download Community Overlays 1 - CBBE Male and Female Repackage.zip (GoogleDriveDownloader+State|1DMWc4kzWRm-Cwtn3EAmIiRo7p1bJmx15)

**To Reproduce**
Attempt an installation of the modlist. Have that installation fail due to missing archives. Groan at having almost reached the end of a Wabbajack install without Nexus Premium that has already taken more than a dozen hours. Head to Github to beg for help.

**Expected behavior**
All required files should have downloaded, I suppose there must be some upstream updates which need to be addressed by the Wabbajack installer or something to change file names.

**Screenshots**
One screenshot attached.
![failed install screenshot](https://user-images.githubusercontent.com/101977570/159163024-eb125cce-e757-43e9-9ffd-e46fdd78351c.png)

**Additional context**
I already tried turning on the Network Workaround. It didn't help.

Log:
[Wabbajack.current.log](https://github.com/ForgottenGlory/Masterstroke/files/8311239/Wabbajack.current.log)

**Comment by ForgottenGlory** [comment]
Not a bug.

**Comment by ghost** [comment]
"Not a bug"? Okay then, semantics aside, it's an issue. I see someone else struggled with it yesterday.

I tried running the new Beta 3 Wabbajack file and it managed to download one or two more files but some still won't work. Specifically, SE.rar and Community Overlays 1. I manually downloaded SE.rar from the mega link in my log and it seemed to do the trick. Still not able to download Community Overlays though.

Not sure how to change the label from "new bug" to something more descriptive of this issue.

**Comment by ForgottenGlory** [comment]
This isn't an issue which you'd know if you spent 30 seconds looking on Discord.
